[package]
name = "hyper11-playground"
version = "0.1.0"
authors = ["Christian <krampenschiesser@gmail.com>"]

[dependencies]
hyper = "0.11"
tokio-tls = "0.1.3"

route-recognizer = "0.1"
url = "1.5.1"
serde = "1.0.10"
serde_json = "1.0.2"

[dev-dependencies]
reqwest = "0.7.1"
